#	'container-registry.oracle.com',
#	'nvcr.io',
#	'registry.gitlab.com',
#	'registry.suse.com',
# 	'public.ecr.aws',

unqualified-search-registries = [
	'ghcr.io',
	'registry.access.redhat.com',
	'registry.fedoraproject.org',
	'registry.opensuse.org',
	'quay.io',
	'docker.io'
]
