#! /usr/bin/env bash

# Copyright © 2026 Boian Berberov
#
# Licensed under the EUPL-1.2 only.
# License text: https://joinup.ec.europa.eu/collection/eupl/eupl-text-eupl-12
# SPDX-License-Identifier: EUPL-1.2

_git_gc()
{
	__gitcomp '
		--aggressive
		--auto
		--cruft
		--detach
		--expire-to=
		--force
		--keep-largest-pack
		--max-cruft-size=
		--no-cruft
		--no-detach
		--no-prune
		--prune=
		--quiet
	'
}
