#! /usr/bin/env bash

# Copyright © 2024, 2026 Boian Berberov
#
# Licensed under the EUPL-1.2 only.
# License text: https://joinup.ec.europa.eu/collection/eupl/eupl-text-eupl-12
# SPDX-License-Identifier: EUPL-1.2

_git_rev_list()
{
	# shellcheck disable=SC2154
	case "${cur}" in
		--*)
			__gitcomp_builtin rev-list
			return
		;;
	esac

	__git_complete_refs
}
