#! /usr/bin/env bash

# Copyright © 2026 Boian Berberov
#
# Licensed under the EUPL-1.2 only.
# License text: https://joinup.ec.europa.eu/collection/eupl/eupl-text-eupl-12
# SPDX-License-Identifier: EUPL-1.2

# WARNING: the upstream completion overrides this one if it's not disabled

_git_symbolic_ref()
{
	case "${words[__git_cmd_idx+1]}" in
		-m)
			# shellcheck disable=SC2154
			case "${prev}" in
				-m)
					:
				;;
				HEAD | refs/* )
					__gitcomp "$(__git for-each-ref --format='%(refname)')"
				;;
				*)
					__gitcomp "$(__git for-each-ref --include-root-refs --format='%(if)%(symref)%(then)%(refname)%(end)' --exclude=refs/tags)"
				;;
			esac
		;;
		-d | --delete )
			# shellcheck disable=SC2154
			case "${cur}" in
				--*)
					__gitcomp '--quiet'
				;;
				*)
					__gitcomp "$(__git for-each-ref --include-root-refs --format='%(if)%(symref)%(then)%(refname)%(end)' --exclude=refs/tags)"
				;;
			esac
		;;
		*)
			# shellcheck disable=SC2154
			case "${prev}" in
				--* | symbolic-ref)
					# shellcheck disable=SC2154
					case "${cur}" in
					--*)
						__gitcomp_builtin symbolic-ref
					;;
					*)
						__gitcomp "$(__git for-each-ref --include-root-refs --format='%(if)%(symref)%(then)%(refname)%(end)' --exclude=refs/tags)"
					;;
					esac
				;;
				HEAD | refs/* )
					:
				;;
				*)
					__gitcomp "$(__git for-each-ref --include-root-refs --format='%(if)%(symref)%(then)%(refname)%(end)' --exclude=refs/tags)"
				;;
			esac
		;;
	esac
}
