#! /usr/bin/env bash

# Copyright © 2024 Boian Berberov
#
# Licensed under the EUPL-1.2 only.
# License text: https://joinup.ec.europa.eu/collection/eupl/eupl-text-eupl-12
# SPDX-License-Identifier: EUPL-1.2

complete -W '
	-m
	--color-mode
	-f
	--force-color
	--color-picker
	-h
	--help
	-V
	--version
	color
	list
	random
	distinct
	sort-by
	pick
	format
	paint
	gradient
	mix
	colorblind
	set
	saturate
	desaturate
	lighten
	darken
	rotate
	complement
	gray
	to-gray
	textcolor
	colorcheck
	help
' pastel
