#! /usr/bin/env bash

# Copyright © 2024 Boian Berberov
#
# Licensed under the EUPL-1.2 only.
# License text: https://joinup.ec.europa.eu/collection/eupl/eupl-text-eupl-12
# SPDX-License-Identifier: EUPL-1.2

if [[ \
	-f /usr/share/bash-completion/completions/git \
	&& "$(head -1 /usr/share/bash-completion/completions/git)" \
	== '# bash/zsh completion support for core Git.' \
]]
then
source /usr/share/bash-completion/completions/git

complete -W "
	$__git_log_common_options
" qgit
fi
