#! /usr/bin/env bash

# Copyright © 2024, 2026 Boian Berberov
#
# Licensed under the EUPL-1.2 only.
# License text: https://joinup.ec.europa.eu/collection/eupl/eupl-text-eupl-12
# SPDX-License-Identifier: EUPL-1.2

_comp_cmd_xdg_user_dir()
{
	# shellcheck disable=SC2034
	local cur prev words cword comp_args
	_comp_initialize -- "$@" || return

	if   (( 1 == cword ))
	then
		_comp_compgen -- -W '
			DESKTOP
			DOCUMENTS
			DOWNLOAD
			MUSIC
			PICTURES
			PROJECTS
			PUBLICSHARE
			TEMPLATES
			VIDEOS
		'
	fi
} && complete -F _comp_cmd_xdg_user_dir xdg-user-dir
