# V5 features that were the mkfs defaults when the upstream Linux 6.12 LTS
# kernel was released at the end of 2024.

[block]
size=4k

[metadata]
bigtime=1
crc=1
finobt=1
inobtcount=1
metadir=0
reflink=1
rmapbt=1
autofsck=0

# [data]
# agcount=
# agsize=
# cowextsize=32
# name=
# su=
# sw=
# extszinherit=
# concurrency=

[inode]
# size=512
# perblock=8
maxpct=10
sparse=1
nrext64=1
# exchange=1 TEST

[log]
# agnum=
internal=1
# logdev=
# size=
# su=
# concurrency=

# [naming]
# size=
# parent=1 TEST

# [sector]
# size=512
