# V5 features that were the mkfs defaults when the upstream Linux 6.12 LTS
# kernel was released at the end of 2024.

[block]
size=16k

[metadata]
bigtime=1
crc=1
# Free inode btree index in each allocation group
finobt=1
inobtcount=1
# Internal directory tree to store filesystem metadata (Linux 6.13)
metadir=1
# Reference count btree index in each allocation group (CoW)
reflink=0
# Reverse-mapping btree index in each allocation group
rmapbt=1
autofsck=0

# [data]
# agcount=
# agsize=
# cowextsize=32
# name=
# su=
# sw=
# extszinherit=
# concurrency=

[inode]
# size=512
# perblock=8
maxpct=2
sparse=1
nrext64=1
# Defaults to 1 with metadata.metadir=1
# exchange=0

[log]
# agnum=
internal=1
# logdev=
# size=
# su=
# concurrency=

[naming]
# Directory block size
# size=
# Back references from child files to parent directories
parent=1

# [sector]
# size=512
